'use strict';
const $=s=>document.querySelector(s);
let findings=[],evidence=[],catalog=[],map={targets:[],candidates:[]},previewPayload=null,toastTimer;
const runResults=new Map();
let currentSuggestions=[];
let emailContacts=[],emailDrafts=[],activeDraft=null,draftDirty=false,draftBusy=false;
const views={drafts:'Prepare, review, and save email drafts. Sender infrastructure can be configured later.',scope:'Define and save the authorized target ranges and domains before working with evidence or checks.',review:'Import output, inspect linked evidence, and correct findings.',analysis:'Choose a local model and analyze stored evidence.',checks:'Review grounded checks, then run a check against an authorized local target.'};
const viewTitles={scope:'Scope',review:'Findings',analysis:'Analysis',checks:'Next checks',drafts:'Email drafts'};
const emptyScope=()=>({cidrs:[],domains:[]});
let savedScope=emptyScope(),scopeLoaded=false,scopeLoadError='';
const scopeLabel=()=>[savedScope.cidrs.join(', '),savedScope.domains.length?'domains: '+savedScope.domains.join(', '):''].filter(Boolean).join(' · ');
function showView(){const hash=location.hash.slice(1);const view=hash==='recon'?'scope':hash;const selected=views[view]?view:'scope';document.body.dataset.view=selected;$('#viewTitle').textContent=viewTitles[selected];document.title=viewTitles[selected]+' · Yagura';$('#viewIntro').textContent=views[selected];document.querySelectorAll('.nav a,.mobile-nav a').forEach(a=>{const active=a.hash==='#'+selected&&!a.hasAttribute('data-nav-parent');a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});$('#actionsNav').classList.toggle('active-parent',['checks','drafts'].includes(selected));$('#checksSubnav').hidden=!['checks','drafts'].includes(selected);$('#checksSubnav').querySelectorAll('a').forEach(a=>{const active=a.hash==='#'+selected;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});updateScopeGate();window.scrollTo(0,0);}
function updateScopeGate(){
  const ready=scopeLoaded&&savedScope.cidrs.length>0;
  document.body.dataset.scopeState=ready?'ready':scopeLoaded?'required':scopeLoadError?'error':'loading';
  $('#scopeGate').hidden=document.body.dataset.view==='scope'||ready;
  $('#scopeGateTitle').textContent=scopeLoadError?'Target scope could not be loaded':!scopeLoaded?'Loading target scope…':'Define the target scope first';
  $('#scopeGateMessage').textContent=scopeLoadError?'The saved scope could not be verified. Open Scope and refresh to retry. '+scopeLoadError:!scopeLoaded?'Checking the saved engagement scope.':'Save an authorized target range to continue to Next checks, then review Findings and Analysis. Next checks and Email drafts are available under Actions. This server’s network is not the target network.';
  $('#savedScopeDisplay').textContent=scopeLabel()||'Not defined';
  $('#scanBtn').disabled=!ready;
  const scanState=$('#scanState');if(!ready||scanState.textContent.startsWith('Save the target scope')||scanState.textContent.startsWith('Saved scope:'))scanState.textContent=ready?'Saved scope: '+scopeLabel()+'. Confirm authorization before discovery.':'Save the target scope before running discovery.';
}
window.addEventListener('hashchange',showView);showView();
function openImport(){location.hash='#review';showView();if(!checkScope()||!scopeLoaded)return;$('#importPanel').open=true;$('#imports').scrollIntoView({block:'start'});$('#importTool').focus();}
document.addEventListener('click',event=>{if(event.target.closest('[data-open-import]'))openImport();});
let workspaceReady=false;
function updatePrerequisites(){
  const hasFindings=workspaceReady&&scopeLoaded&&!!checkScope()&&findings.length>0;
  $('#analyzeBtn').disabled=!hasFindings;
  $('#analysisPrerequisite').hidden=hasFindings;
  $('#analysisPrerequisite').innerHTML=workspaceReady?'No findings to analyze yet. <button class="ref" data-open-import>Import output</button> or <a href="#scope">discover hosts</a> first.':'Findings are unavailable. Refresh the workspace to retry.';
  const eligible=workspaceReady&&checkScope()&&map.candidates.length>0;
  $('#suggestBtn').disabled=!eligible;
  $('#checksPrerequisite').hidden=!!eligible;
  $('#checksPrerequisite').innerHTML=!workspaceReady?'Check prerequisites are unavailable. Refresh the workspace to retry.':!checkScope()?'Set an <a href="#scope">authorized range in Scope</a> before selecting checks.':!findings.length?'No findings recorded. <button class="ref" data-open-import>Import output</button> or <a href="#scope">discover hosts</a> first.':'No checks are available for the recorded hosts in this range. Review <a href="#review">target evidence</a> or <a href="#scope">change the range</a>.';
}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3500);}
async function api(url,options={}){const r=await fetch(url,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>null);if(!r.ok){const missingApi=r.status===404&&(!d||d.error==='Not found.');const error=new Error(missingApi?`Yagura API is unavailable at ${location.origin}. Run python3 main.py on the machine serving this page and open its configured app address.`:d?.error||`Request failed (HTTP ${r.status}).`);error.message+=` (${url})`;error.status=r.status;throw error;}if(!d)throw new Error('The server returned an invalid API response. Check that this page is served by Yagura.');return d;}
const post=(url,data)=>api(url,{method:'POST',body:JSON.stringify(data)});
const checkScope=()=>savedScope.cidrs.length?savedScope:null;
const showScope=()=>{$('#checksScopeDisplay').textContent=scopeLabel()||'No range set';};
let scopeSave=Promise.resolve();
async function saveScope(clear=false){
  const split=value=>value.split(/[\s,]+/).map(x=>x.trim()).filter(Boolean);
  const value=clear?emptyScope():{cidrs:split($('#cidrs').value),domains:split($('#domains').value)};
  if(!clear&&!value.cidrs.length)throw new Error('Enter at least one authorized target IPv4 range.');
  if(!clear&&!$('#scopeAuthorized').checked)throw new Error('Confirm that these target ranges and domains are approved before saving.');
  scopeSave=scopeSave.catch(()=>{}).then(()=>api('/api/scope',{method:'PUT',body:JSON.stringify(value)}));
  const result=await scopeSave;
  savedScope=result;scopeLoaded=true;scopeLoadError='';$('#cidrs').value=savedScope.cidrs.join('\n');$('#domains').value=savedScope.domains.join('\n');$('#scanTarget').value=savedScope.domains.length?'':savedScope.cidrs[0]||'';
  $('#authorized').checked=false;$('#checksAuthorized').checked=false;$('#scanResults').innerHTML='';
  showScope();updateScopeGate();updatePrerequisites();
  $('#scopeState').textContent=checkScope()?'Saved target scope: '+scopeLabel()+'. Other workflow sections are now available.':'Scope cleared. Save a target range to continue.';
  if(checkScope()){location.hash='#checks';showView();}
  await refreshFindings();return result;
}
async function persistScope(clear=false){const button=$('#saveScope');button.disabled=true;$('#clearScope').disabled=true;try{await saveScope(clear);toast(clear?'Target scope cleared':'Target scope saved');}catch(e){$('#scopeState').textContent=e.message;}finally{button.disabled=false;$('#clearScope').disabled=false;}}
$('#saveScope').onclick=()=>persistScope();$('#clearScope').onclick=()=>persistScope(true);

function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function date(s){return s?new Date(s).toLocaleString():'';}
function ref(id,label){return `<button class="ref" data-ref="${esc(id)}">${esc(label)}</button>`;}
function evidenceLinks(ids){return (ids||[]).map(id=>ref(id,evidence.find(e=>e.id===id)?.command || 'Source evidence')).join(' · ');}
function recordLabel(f){const h=findings.find(x=>x.id===f.hostId);return f.kind==='host'?`${f.ip}${f.name?' · '+f.name:''}`:f.kind==='service'?`${h?.ip||'Host'} · ${f.port}/${f.protocol} ${f.name||''}`:f.title;}
function wireRefs(parent){parent.querySelectorAll('[data-ref]').forEach(b=>b.onclick=()=>showRecord(b.dataset.ref));}
function showDialog(title,body){$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=body;if(!$('#reviewDialog').open)$('#reviewDialog').showModal();wireRefs($('#dialogBody'));}
$('#closeDialog').onclick=()=>$('#reviewDialog').close();
function showRecord(id){
  const e=evidence.find(x=>x.id===id);
  if(e){showDialog('Source evidence',`<p class="mono">${esc(e.command)}</p><p class="notice">${esc(e.tool)} · ${esc(e.format)} · Observed ${esc(date(e.observedAt))} · Imported ${esc(date(e.importedAt))}</p><pre>${esc(e.output)}</pre>`);return;}
  const f=findings.find(x=>x.id===id);if(!f)return;
  showDialog(recordLabel(f),`<p class="notice">${esc(f.kind)} · ${esc(f.reviewStatus)} · First seen ${esc(date(f.firstSeen))} · Last seen ${esc(date(f.lastSeen))}</p><pre>${esc(f.detail||JSON.stringify(Object.fromEntries(Object.entries(f).filter(([k])=>!['id','evidenceIds','createdAt','updatedAt'].includes(k))),null,2))}</pre><p>${f.hostId?ref(f.hostId,'Linked host'):''} ${f.serviceId?ref(f.serviceId,'Linked service'):''}</p><p>${evidenceLinks(f.evidenceIds)}</p><button class="btn" id="detailEdit">Edit / mark reviewed</button>`);
  $('#detailEdit').onclick=()=>editRecord(f.id);
}
function renderFindings(){
  $('#findingCount').textContent=`${findings.length} records · ${findings.filter(f=>f.reviewStatus!=='reviewed').length} need review`;
  const filter=$('#findingFilter').value,rows=findings.filter(f=>filter==='all'||filter==='unreviewed'&&f.reviewStatus!=='reviewed'||f.kind===filter);
  const box=$('#findingList');
  box.innerHTML=rows.length?rows.map(f=>`<div class="item"><div class="item-left"><strong>${ref(f.id,recordLabel(f))}</strong><small>${esc(f.kind==='service'?`${f.state} · ${f.product||''} ${f.version||''}`:f.kind==='host'?`${f.state}${f.local?' · local interface':''}`:f.detail.slice(0,180))}</small><small>${esc(date(f.lastSeen))} · <span class="${f.reviewStatus==='reviewed'?'reviewed':''}">${esc(f.reviewStatus)}</span> · ${f.evidenceIds.length} source(s)</small></div><span class="kind">${esc(f.kind)}</span><div class="item-actions"><button class="btn" data-edit="${esc(f.id)}">Edit</button><button class="btn" data-merge="${esc(f.id)}">Merge</button><button class="btn" data-delete="${esc(f.id)}">Delete</button></div></div>`).join(''):'<div class="empty">No matching findings. <button class="ref" data-open-import>Import command output</button>, add an observation above, or change the filter.</div>';
  wireRefs(box);box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editRecord(b.dataset.edit));box.querySelectorAll('[data-merge]').forEach(b=>b.onclick=()=>mergeRecord(b.dataset.merge));box.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteRecord(b.dataset.delete));
}
function renderMap(){
  $('#targetCount').textContent=`${map.targets.length} hosts · ${findings.filter(f=>f.kind==='service').length} services`;
  const box=$('#targets');
  box.innerHTML=map.targets.length?map.targets.map(t=>`<div class="cmd"><div class="cmdtop"><strong>${ref(t.host.id,recordLabel(t.host))}</strong><span class="kind">${esc(t.stage)}</span></div><p>${esc(t.host.state)} · ${t.observations.length} observations${t.scopeReason?' · '+esc(t.scopeReason):''}</p><div class="target-services">${t.services.length?t.services.map(s=>`<div>${ref(s.id,`${s.port}/${s.protocol} · ${s.state} · ${s.name||'unknown'} ${s.product||''} ${s.version||''}`)}</div>`).join(''):'<span class="hint">No services recorded. Import a port scan to extend this map.</span>'}</div><p>${evidenceLinks(t.host.evidenceIds)}</p></div>`).join(''):'<div class="empty">No targets recorded yet. <button class="ref" data-open-import>Import command output</button> or <a href="#scope">discover hosts in Scope</a> to build this map.</div>';
  wireRefs(box);
}
function copyButtons(box){box.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);toast(b.dataset.template==='true'?'Template copied; replace placeholders before running.':'Command copied');}catch{toast('Clipboard access unavailable; select the command to copy.');}});}
function renderCatalog(){const box=$('#catalog');$('#catalogCount').textContent=`${catalog.length} reference templates`;box.innerHTML=catalog.map(c=>{const template=/\{[^}]+\}/.test(c.command);return `<details class="cmd catalog-item"><summary class="catalog-item-toggle"><strong>${esc(c.title)}</strong></summary><div class="catalog-item-body"><p>${esc(c.when)}</p>${c.executable===false?'<p class="notice">Reference only · collect output manually and import as general evidence.</p>':''}<code>${esc(c.command)}</code>${template?'<p class="notice warning">Replace the values in braces before running this command.</p>':''}<div class="toolbar"><button class="btn" data-copy="${esc(c.command)}" data-template="${template}">${template?'Copy template':'Copy'}</button></div></div></details>`;}).join('');copyButtons(box);}
function renderSuggestions(items){currentSuggestions=items;const box=$('#suggestions');box.innerHTML=items.length?items.map(s=>{const result=runResults.get(s.id);return `<div class="cmd"><div class="cmdtop"><strong>${esc(s.title)}</strong><div class="cmd-actions"><button class="btn" data-copy="${esc(s.command)}">Copy</button><button class="btn" data-edit-run="${esc(s.id)}">Edit &amp; run</button><button class="btn primary" data-run="${esc(s.id)}">Run</button></div></div><p>${esc(s.reason)}</p><code>${esc(s.command)}</code><p>Based on ${s.findingIds.map(id=>ref(id,recordLabel(findings.find(f=>f.id===id)||{title:id}))).join(' · ')}</p><p>${evidenceLinks(s.evidenceIds)}</p>${result?`<div class="run-output"><p class="status">${result.ok?'Completed':'Failed'}${result.imported?' · Findings updated':''}${result.warning?' · '+esc(result.warning):''}</p><code>${esc(result.command)}</code><pre>${esc(result.output||result.stderr||'No output.')}</pre></div>`:''}</div>`;}).join(''):'<div class="empty">Enter an authorized check range to see commands for recorded hosts inside it.</div>';copyButtons(box);wireRefs(box);box.querySelectorAll('[data-run]').forEach(b=>b.onclick=()=>runCheck(b,items.find(s=>s.id===b.dataset.run)));box.querySelectorAll('[data-edit-run]').forEach(b=>b.onclick=()=>editAndRun(items.find(s=>s.id===b.dataset.editRun)));}
function editAndRun(suggestion){showDialog('Edit check command',`<p class="notice">The target, program and required options stay fixed. You can change ping count (1–5), Nmap top ports (1–1000), recorded service ports or version level, and HTTP header timeout (1–20 seconds) or same-origin path. Other checks can be rerun unchanged.</p><div class="field"><label for="editedCheckCommand">Command to run</label><textarea id="editedCheckCommand" rows="4" spellcheck="false">${esc(suggestion.command)}</textarea></div><p class="status" id="editedCheckState" role="status">Review the command and confirm authorization in Next checks.</p><button class="btn primary" id="confirmEditedCheck">Run edited command</button>`);$('#confirmEditedCheck').onclick=async()=>{const command=$('#editedCheckCommand').value.trim();const button=$('#confirmEditedCheck');if(!command){$('#editedCheckState').textContent='Enter a command.';return;}if(!checkScope()||!$('#checksAuthorized').checked){$('#editedCheckState').textContent='Save a target scope and confirm check authorization in Next checks first.';return;}button.disabled=true;$('#editedCheckState').textContent='Running edited command…';const ok=await runCheck(button,suggestion,command);if(!ok&&$('#reviewDialog').open)button.disabled=false;};$('#editedCheckCommand').focus();}
async function runCheck(button,suggestion,editedCommand){if(!checkScope()){$('#suggestState').textContent='Set an authorized scope first.';location.hash='#scope';setTimeout(()=>$('#cidrs').focus(),0);return false;}if(!$('#checksAuthorized').checked){$('#suggestState').textContent='Confirm authorization before running a check.';$('#checksAuthorized').focus();return false;}button.disabled=true;$('#suggestState').textContent=`Running ${editedCommand||suggestion.command}…`;try{await scopeSave;const result=await post('/api/checks/run',{candidateId:suggestion.id,authorized:true,authorizedScope:checkScope(),...(editedCommand!==undefined?{editedCommand}:{})});runResults.set(suggestion.id,result);if(result.imported)await refreshFindings();else renderSuggestions(currentSuggestions);showDialog('Check output',`<p class="mono">${esc(result.command)}</p><p class="status">${result.ok?'Completed':'Failed'}${result.imported?' · Findings updated':''}${result.warning?' · '+esc(result.warning):''}</p><pre>${esc(result.output||result.stderr||'No output.')}</pre>`);$('#suggestState').textContent=result.ok?'Check finished. Review the output and updated findings.':`Check failed: ${result.stderr||'See output below.'}`;return true;}catch(e){$('#suggestState').textContent=e.message;if(editedCommand!==undefined&&$('#editedCheckState'))$('#editedCheckState').textContent=e.message;return false;}finally{button.disabled=false;}}
function renderAnalysis(result){
  const box=$('#analysisResults');
  if(!result){box.innerHTML='<div class="empty">No saved analysis. Import findings and select an analysis scope.</div>';return;}
  box.innerHTML=`<div class="cmd"><strong>${esc(result.source)}${result.model?' · '+esc(result.model):''}</strong><p>${esc(result.summary)}</p><p>${esc(date(result.generatedAt))}${result.stale?' · Findings changed since this analysis. Analyze again.':''}</p><p class="notice">${esc(result.message)}</p>${result.error?`<p class="notice warning">${esc(result.error.message)}</p>`:''}${result.warnings.map(w=>`<p class="notice warning">${esc(w)}</p>`).join('')}</div>`+result.assessments.map(a=>`<div class="cmd"><strong>${result.source==='local model'?'Model interpretation · review required':'Recorded facts'}</strong><p>${esc(a.interpretation)}</p>${a.uncertainties.map(u=>`<p class="notice">Uncertainty: ${esc(u)}</p>`).join('')}<p>${a.findingIds.map(id=>ref(id,recordLabel(findings.find(f=>f.id===id)||{title:'Previous finding'}))).join(' · ')}</p><p>${evidenceLinks(a.evidenceIds)}</p></div>`).join('');
  box.innerHTML+=(result.hypotheses||[]).map(h=>`<div class="cmd"><div class="cmdtop"><strong>${esc(h.title)}</strong><span class="kind">Model path hypothesis · review required</span></div><p>${esc(h.summary)}</p><ol>${h.steps.map(step=>`<li><p><strong>${esc(step.status)}</strong> · ${esc(step.claim)}</p><p>${step.findingIds.map(id=>ref(id,recordLabel(findings.find(f=>f.id===id)||{title:'Previous finding'}))).join(' · ')}</p><p>${evidenceLinks(step.evidenceIds)}</p></li>`).join('')}</ol>${[['Prerequisites',h.prerequisites],['Missing evidence',h.missingEvidence],['Counterevidence',h.counterevidence]].map(([label,items])=>items.length?`<strong>${label}</strong><ul>${items.map(item=>`<li>${esc(item)}</li>`).join('')}</ul>`:'').join('')}${h.investigations.length?`<strong>Proposed investigations · manual review</strong>${h.investigations.map(i=>`<div class="cmd"><p>${esc(i.objective)}</p><p>${i.hostIds.map(id=>ref(id,recordLabel(findings.find(f=>f.id===id)||{title:'Previous host'}))).join(' · ')}</p><p>Expected evidence: ${esc(i.expectedEvidence)}</p><p>Decision impact: ${esc(i.decisionImpact)}</p></div>`).join('')}`:''}</div>`).join('');
  wireRefs(box);
}
async function loadAnalysis(){try{const d=await api('/api/analysis/latest');renderAnalysis(d.analysis);}catch(e){$('#analysisState').textContent=e.message;}}
$('#analyzeBtn').onclick=async()=>{const b=$('#analyzeBtn');b.disabled=true;$('#analysisState').textContent='Analyzing recorded findings…';try{await scopeSave;const hostId=$('#analysisHost').value,model=$('#llmModel').value;const d=await post('/api/analysis',{...(hostId?{hostId}:{}),...(model?{model}:{}),...(checkScope()?{authorizedScope:checkScope()}:{})});renderAnalysis(d);renderSuggestions(d.suggestions);$('#analysisState').textContent=`${d.source}: ${d.status}${d.stale?' · findings changed during analysis':''}`;}catch(e){$('#analysisState').textContent=e.message;}finally{updatePrerequisites();}};
async function loadModels(){const h=await api('/api/llm/health'),select=$('#llmModel'),selected=select.value;select.innerHTML='<option value="">Server default / automatic</option>'+(h.models||[]).map(id=>`<option value="${esc(id)}">${esc(id)}</option>`).join('');select.value=(h.models||[]).includes(selected)?selected:'';$('#analysisState').textContent=h.status==='ready'?`Model ready: ${h.model}`:h.status==='model-required'?'Choose one of the available models.':`Model ${h.status}: ${h.message}`;$('#llmBadge').textContent=h.status==='ready'||h.status==='model-required'?'LOCAL MODEL AVAILABLE':'LOCAL MODEL UNAVAILABLE';}
$('#llmHealthBtn').onclick=async()=>{const b=$('#llmHealthBtn');b.disabled=true;$('#analysisState').textContent='Testing model endpoint…';try{await loadModels();}catch(e){$('#analysisState').textContent=e.message;}finally{b.disabled=false;}};
async function refreshFindings(){const scope=checkScope(),[doc,w]=await Promise.all([api('/api/findings'),api('/api/workflow')]);findings=doc.findings;evidence=doc.evidence;map=w;workspaceReady=true;updatePrerequisites();const selected=$('#analysisHost').value;$('#analysisHost').innerHTML=options(findings.filter(f=>f.kind==='host'&&w.targets.some(t=>t.host.id===f.id&&t.eligible)),selected,'All scoped findings');renderFindings();renderMap();renderSuggestions(w.candidates);$('#suggestState').textContent=scope?'Built-in next checks limited to '+scopeLabel()+'.':'Enter an authorized scope to see proposed commands.';await loadAnalysis();await loadDraftContacts();}
async function load(){scopeLoaded=false;scopeLoadError='';updateScopeGate();try{const [h,c,scope]=await Promise.all([api('/api/health'),api('/api/commands'),api('/api/scope')]);savedScope=scope;scopeLoaded=true;scopeLoadError='';$('#cidrs').value=scope.cidrs.join('\n');$('#domains').value=scope.domains.join('\n');$('#scanTarget').value=scope.domains.length?'':scope.cidrs[0]||'';showScope();updateScopeGate();$('#scopeState').textContent=checkScope()?'Saved target scope: '+scopeLabel()+'.':'Save a target scope to enable the other workflow sections.';catalog=c.commands;renderCatalog();await refreshFindings();await refreshDrafts();$('#systemStatus').innerHTML=`nmap: <b>${h.nmap?'ready':'not found'}</b> · nuclei: <b>${h.nuclei?'ready':'not found'}</b>`;$('#llmBadge').textContent=h.llm==='configured'?'LOCAL MODEL AVAILABLE':h.llm.startsWith('blocked')?'LLM URL BLOCKED':'LOCAL MODEL OPTIONAL';loadModels().catch(e=>{$('#analysisState').textContent=e.message;});return true;}catch(e){$('#systemStatus').textContent='Workspace API unavailable: '+e.message+' Refresh to retry.';workspaceReady=false;if(!scopeLoaded){scopeLoadError=e.message;updateScopeGate();$('#scopeState').textContent='Cannot load the target scope: '+e.message;}updatePrerequisites();return false;}}
function field(key,label,value,type='text'){return `<div class="field"><label for="edit-${key}">${esc(label)}</label><input id="edit-${key}" name="${key}" type="${type}" value="${esc(value)}"></div>`;}
function options(rows,selected,emptyLabel='Unlinked'){return `<option value="">${esc(emptyLabel)}</option>`+rows.map(f=>`<option value="${esc(f.id)}" ${f.id===selected?'selected':''}>${esc(recordLabel(f))}</option>`).join('');}
function editRecord(id){
  const f=findings.find(x=>x.id===id);let extra='';
  if(f.kind==='host')extra=field('ip','IP address',f.ip)+field('name','Hostname',f.name)+field('state','Host state (up, down, no-response, unknown)',f.state)+field('mac','MAC address',f.mac)+field('interface','Interface',f.interface)+field('prefix','Address prefix length (optional)',f.prefix,'number')+field('neighborState','Neighbor state',f.neighborState)+field('aliases','Other IP addresses (comma separated)',(f.aliases||[]).join(', '))+`<label class="check"><input name="local" type="checkbox" ${f.local?'checked':''}>Local interface address</label>`;
  if(f.kind==='service')extra=field('port','Port',f.port,'number')+`<div class="field"><label for="edit-protocol">Protocol</label><select id="edit-protocol" name="protocol">${['tcp','udp','sctp'].map(p=>`<option ${p===f.protocol?'selected':''}>${p}</option>`).join('')}</select></div>`+['state','name','product','version','tunnel'].map(k=>field(k,k[0].toUpperCase()+k.slice(1),f[k])).join('');
  if(f.kind==='observation')extra=`<div class="field"><label for="edit-hostId">Linked host</label><select id="edit-hostId" name="hostId">${options(findings.filter(x=>x.kind==='host'),f.hostId)}</select></div><div class="field"><label for="edit-serviceId">Linked service (sets host)</label><select id="edit-serviceId" name="serviceId">${options(findings.filter(x=>x.kind==='service'),f.serviceId)}</select></div>`;
  showDialog('Edit finding',`<form id="editForm">${field('title','Title',f.title)}${extra}<div class="field"><label for="edit-detail">Observation / detail</label><textarea id="edit-detail" name="detail">${esc(f.detail)}</textarea></div><p class="notice">Saving marks this finding reviewed. Future imports retain your corrected fields and add source evidence.</p><p class="status" id="editError" role="status"></p><button class="btn primary">Save & mark reviewed</button></form>`);
  $('#editForm').onsubmit=async event=>{event.preventDefault();const patch=Object.fromEntries(new FormData(event.target));if(f.kind==='host'){patch.local=event.target.elements.local.checked;patch.aliases=String(patch.aliases||'').split(',').map(x=>x.trim()).filter(Boolean);}try{await api('/api/findings/'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify(patch)});$('#reviewDialog').close();await refreshFindings();toast('Finding updated');}catch(e){$('#editError').textContent=e.message;}};
}
function mergeRecord(id){
  const f=findings.find(x=>x.id===id),choices=findings.filter(x=>x.id!==id&&x.kind===f.kind&&(f.kind!=='service'||x.hostId===f.hostId&&x.port===f.port&&x.protocol===f.protocol));
  showDialog('Merge duplicate findings',`<p class="notice">Keep ${esc(recordLabel(f))}. Merge source evidence and linked records from the selected duplicate into it. Host merges retain the other address as an alias and combine matching services.</p>${choices.length?`<form id="mergeForm"><div class="field"><label for="mergeSource">Duplicate to merge</label><select id="mergeSource" required>${options(choices,null,'Choose a duplicate')}</select></div><p class="status" id="mergeError" role="status"></p><button class="btn primary">Merge into this finding</button></form>`:'<div class="empty">No compatible duplicates available.</div>'}`);
  if(choices.length)$('#mergeForm').onsubmit=async e=>{e.preventDefault();try{await post('/api/findings/merge',{targetId:id,sourceId:$('#mergeSource').value});$('#reviewDialog').close();await refreshFindings();toast('Findings merged');}catch(error){$('#mergeError').textContent=error.message;}};
}
function deleteRecord(id){const f=findings.find(x=>x.id===id);showDialog('Delete finding',`<p>Delete ${esc(recordLabel(f))}?</p><p class="notice">${f.kind==='host'?'Its linked services and observations will also be removed.':f.kind==='service'?'Its linked observations will also be removed.':''} Raw source evidence remains available in the JSON export.</p><button class="btn" id="confirmDelete">Delete finding</button>`);$('#confirmDelete').onclick=async()=>{try{await api('/api/findings/'+encodeURIComponent(id),{method:'DELETE'});$('#reviewDialog').close();await refreshFindings();}catch(e){toast(e.message);}};}
$('#findingFilter').onchange=renderFindings;
function invalidatePreview(){previewPayload=null;$('#saveImport').disabled=true;$('#importPreview').innerHTML='';$('#importState').textContent='Preview the updated output before saving.';}
for(const id of ['importTool','importCommand','importOutput','importTime','importEvidenceTitle','importEvidenceIp'])$('#'+id).addEventListener('input',invalidatePreview);
$('#importFile').onchange=async()=>{const file=$('#importFile').files[0];if(!file)return;if(file.size>800000){toast('File exceeds the 800 KB limit.');return;}$('#importOutput').value=await file.text();invalidatePreview();};
$('#previewImport').onclick=async()=>{
  const b=$('#previewImport');b.disabled=true;invalidatePreview();$('#importState').textContent='Parsing output…';
  try{const input={tool:$('#importTool').value,...($('#importTool').value==='evidence'?{title:$('#importEvidenceTitle').value.trim()||'Imported investigation evidence',ip:$('#importEvidenceIp').value.trim()}:{}),command:$('#importCommand').value,output:$('#importOutput').value,observedAt:$('#importTime').value?new Date($('#importTime').value).toISOString():undefined};const d=await post('/api/import/preview',input);input.observedAt=d.evidence[0].observedAt;previewPayload=input;$('#saveImport').disabled=false;$('#importState').textContent=`Preview only: ${d.findings.filter(f=>f.kind==='host').length} hosts · ${d.findings.filter(f=>f.kind==='service').length} services · ${d.findings.filter(f=>f.kind==='observation').length} observations. Save, then correct records in Findings. ${d.warnings.join(' ')}`;$('#importPreview').innerHTML=d.findings.slice(0,100).map(f=>`<div class="item"><div class="item-left"><strong>${esc(f.kind==='host'?f.ip:f.kind==='service'?`${f.port}/${f.protocol} ${f.name}`:f.title)}</strong><small>${esc(f.state||f.detail)} ${esc(f.product||'')} ${esc(f.version||'')}</small></div><span class="kind">${esc(f.kind)}</span></div>`).join('')+(d.findings.length>100?'<p class="notice">Showing the first 100 records. All parsed records will be saved.</p>':'');}catch(e){$('#importState').textContent=e.message;}finally{b.disabled=false;}
};
$('#saveImport').onclick=async()=>{if(!previewPayload)return;const b=$('#saveImport');b.disabled=true;try{const d=await post('/api/import',previewPayload);previewPayload=null;await refreshFindings();$('#importState').textContent=`Saved: ${d.summary.added} new records, ${d.summary.linked} existing records linked to new evidence. Review imported details below.`;$('#importPreview').innerHTML='';toast('Import saved');}catch(e){$('#importState').textContent=e.message;b.disabled=false;}};
$('#discoverLocal').onclick=async()=>{const b=$('#discoverLocal'),state=$('#localState');b.disabled=true;state.textContent='Reading…';try{const d=await post('/api/discovery/local',{});$('#interfaces').innerHTML=d.interfaces.length?d.interfaces.map(i=>{return `<div class="item"><div class="item-left"><strong>${esc(i.interface)}</strong><small class="mono">${esc(i.cidr)}</small><small>Yagura server context · not a target range</small></div></div>`;}).join(''):'<div class="empty">No IPv4 interfaces found.</div>';$('#neighbors').innerHTML=d.hosts.length?d.hosts.map(h=>`<div class="item"><div class="item-left"><strong class="mono">${esc(h.ip)}</strong><small>${esc(h.interface)} ${esc(h.state)} ${esc(h.mac)}</small></div></div>`).join(''):'<div class="empty">Neighbor table is empty.</div>';state.textContent=d.errors.join(' · ')||'Server context recorded; target scope unchanged';await refreshFindings();}catch(e){state.textContent=e.message;}finally{b.disabled=false;}};
$('#scanBtn').onclick=async()=>{const b=$('#scanBtn'),state=$('#scanState');b.disabled=true;state.textContent='Running scoped host discovery…';try{if(!scopeLoaded||!checkScope())throw new Error('Save the target scope first.');const d=await post('/api/discovery/scan',{cidr:$('#scanTarget').value.trim(),authorized:$('#authorized').checked});await refreshFindings();$('#scanResults').innerHTML=d.hosts.length?d.hosts.map(h=>`<div class="item"><div class="item-left"><strong>${esc(h.name||h.ip)}</strong><small class="mono">${esc(h.ip)} · ${esc(h.status)}</small></div><button class="btn" data-addhost="${esc(h.ip)}">＋ Note</button></div>`).join(''):'<div class="empty">No hosts reported.</div>';$('#scanResults').querySelectorAll('[data-addhost]').forEach(b=>b.onclick=()=>{$('#findingIp').value=b.dataset.addhost;location.hash='#review';setTimeout(()=>$('#findingTitle').focus(),0);});state.textContent=`Saved ${d.count} hosts and source evidence from ${d.cidr}.`;}catch(e){state.textContent=e.message;}finally{b.disabled=false;}};
$('#addFinding').onclick=async()=>{try{await post('/api/findings',{title:$('#findingTitle').value,ip:$('#findingIp').value.trim(),detail:$('#findingDetail').value});await refreshFindings();for(const id of ['findingTitle','findingIp','findingDetail'])$('#'+id).value='';toast('Observation saved');}catch(e){toast(e.message);}};
for(const id of ['cidrs','domains'])$('#'+id).addEventListener('input',()=>{$('#scopeAuthorized').checked=false;$('#scopeState').textContent='Unsaved change. Confirm approval and select Save target scope. The saved scope remains '+(scopeLabel()||'undefined')+'.';});
$('#suggestBtn').onclick=async()=>{const b=$('#suggestBtn');b.disabled=true;$('#suggestState').textContent='Selecting grounded checks…';try{await scopeSave;const model=$('#llmModel').value,d=await post('/api/suggest',{...(model?{model}:{}),...(checkScope()?{authorizedScope:checkScope()}:{})});renderSuggestions(d.suggestions);$('#suggestState').textContent=`${d.source}${d.model?' · '+d.model:''}: ${d.message}`;}catch(e){$('#suggestState').textContent=e.message;renderSuggestions([]);}finally{updatePrerequisites();}};
$('#refreshAll').onclick=async()=>{const b=$('#refreshAll');b.disabled=true;try{if(await load())toast('Workspace view refreshed');}finally{b.disabled=false;}};
const draftFields={to:'draftTo',sender:'draftSender',senderName:'draftSenderName',subject:'draftSubject',body:'draftBody',notes:'draftNotes'};
function draftValues(){return Object.fromEntries(Object.entries(draftFields).map(([key,id])=>[key,$('#'+id).value]));}
function markDraftDirty(){draftDirty=true;$('#draftState').textContent='Unsaved changes';}
function draftLock(value){draftBusy=value;$('#draftForm').querySelectorAll('input,textarea,button,select').forEach(el=>el.disabled=value);$('#draftList').querySelectorAll('button').forEach(el=>el.disabled=value);}
function showDraftSources(){const address=$('#draftTo').value.trim(),contact=emailContacts.find(c=>c.address.toLowerCase()===address.toLowerCase());$('#draftContact').value=contact?.address||'';const sources=contact?.sources||(activeDraft?.to===address?activeDraft.sourceUrls:[])||[];$('#draftSources').textContent=sources.length?'Found on: '+sources.join(' · '):'You can also enter a recipient manually.';}
async function loadDraftContacts(){const data=await api('/api/email-contacts');emailContacts=data.contacts;$('#draftContact').innerHTML='<option value="">Choose a contact or enter a recipient below</option>'+emailContacts.map(c=>`<option value="${esc(c.address)}">${esc(c.address)}</option>`).join('');showDraftSources();}
function renderDraftList(){const sorted=[...emailDrafts].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));$('#draftCount').textContent=`${sorted.length} ${sorted.length===1?'draft':'drafts'}`;$('#draftList').innerHTML=sorted.length?sorted.map(d=>`<div class="item"><div class="item-left"><strong>${esc(d.subject||'Untitled draft')}</strong><small>${esc(d.to||'Recipient not set')} · ${esc(date(d.updatedAt))}</small><small>${d.sender?esc(d.sender):'Sender pending'}</small></div><div class="item-actions"><button class="btn" data-open-draft="${esc(d.id)}" ${draftBusy?'disabled':''}>Open</button><button class="btn" data-delete-draft="${esc(d.id)}" ${draftBusy?'disabled':''}>Remove</button></div></div>`).join(''):'<div class="empty">No saved drafts yet.</div>';$('#draftList').querySelectorAll('[data-open-draft]').forEach(b=>b.onclick=()=>openDraft(emailDrafts.find(d=>d.id===b.dataset.openDraft)));$('#draftList').querySelectorAll('[data-delete-draft]').forEach(b=>b.onclick=()=>removeDraft(emailDrafts.find(d=>d.id===b.dataset.deleteDraft)));}
async function refreshDrafts(){emailDrafts=(await api('/api/email-drafts')).drafts;renderDraftList();}
function openDraft(draft){if(draftBusy)return;if(draftDirty&&!window.confirm('Discard unsaved changes in the current draft?'))return;activeDraft=draft||null;Object.entries(draftFields).forEach(([key,id])=>$('#'+id).value=draft?.[key]||'');draftDirty=false;showDraftSources();$('#draftState').textContent=draft?'Saved draft · '+date(draft.updatedAt):'New draft · sender can be added later.';$('#draftSubject').focus();}
async function saveEmailDraft(){if(draftBusy||!$('#draftForm').reportValidity())return null;draftLock(true);$('#draftState').textContent='Saving draft…';try{const payload=draftValues(),data=activeDraft?await api('/api/email-drafts/'+encodeURIComponent(activeDraft.id),{method:'PATCH',body:JSON.stringify({...payload,revision:activeDraft.revision})}):await post('/api/email-drafts',payload);activeDraft=data.draft;draftDirty=false;emailDrafts=emailDrafts.filter(d=>d.id!==activeDraft.id).concat(activeDraft);renderDraftList();$('#draftState').textContent='Saved locally · '+date(activeDraft.updatedAt);showDraftSources();return activeDraft;}catch(e){$('#draftState').textContent=e.message;if(e.status===409)await refreshDrafts().catch(()=>{});return null;}finally{draftLock(false);}}
function draftText(d){return (d.sender?`From: ${d.senderName?d.senderName+' <'+d.sender+'>':d.sender}\n`:'')+(d.to?`To: ${d.to}\n`:'')+`Subject: ${d.subject}\n\n${d.body}`;}
function previewEmailDraft(){showDialog('Email preview',`<p class="notice">${$('#draftSender').value?'Draft for review.':'Sender details are pending.'}</p><pre>${esc(draftText(draftValues()))}</pre>`);}
function removeDraft(draft){if(draftBusy)return;showDialog('Remove draft',`<p>Remove ${esc(draft.subject||'Untitled draft')}?</p>${activeDraft?.id===draft.id&&draftDirty?'<p class="notice">Unsaved changes to this draft will also be discarded.</p>':''}<p class="status" id="deleteDraftError"></p><button class="btn" id="confirmRemoveDraft">Remove draft</button>`);$('#confirmRemoveDraft').onclick=async()=>{const button=$('#confirmRemoveDraft');button.disabled=true;draftLock(true);try{await api('/api/email-drafts/'+encodeURIComponent(draft.id),{method:'DELETE',body:JSON.stringify({revision:draft.revision})});emailDrafts=emailDrafts.filter(d=>d.id!==draft.id);if(activeDraft?.id===draft.id){draftDirty=false;draftLock(false);openDraft(null);}renderDraftList();$('#reviewDialog').close();toast('Draft removed');}catch(e){$('#deleteDraftError').textContent=e.message;if(e.status===409)await refreshDrafts().catch(()=>{});button.disabled=false;}finally{draftLock(false);}};}
window.addEventListener('beforeunload',event=>{if(draftDirty){event.preventDefault();event.returnValue='';}});
Object.values(draftFields).forEach(id=>$('#'+id).addEventListener('input',()=>{markDraftDirty();if(id==='draftTo')showDraftSources();}));
$('#draftContact').onchange=()=>{if($('#draftContact').value){$('#draftTo').value=$('#draftContact').value;markDraftDirty();showDraftSources();}};
$('#draftForm').onsubmit=event=>{event.preventDefault();saveEmailDraft();};
$('#newDraft').onclick=()=>openDraft(null);
$('#previewDraft').onclick=previewEmailDraft;
$('#copyDraft').onclick=async()=>{try{await navigator.clipboard.writeText(draftText(draftValues()));toast('Email draft copied');}catch{previewEmailDraft();toast('Select the preview text to copy.');}};
$('#exportDraft').onclick=async()=>{const draft=await saveEmailDraft();if(draft){const link=document.createElement('a');link.href='/api/email-drafts/'+encodeURIComponent(draft.id)+'/export';link.download='email-draft.eml';document.body.append(link);link.click();link.remove();}};
$('#generateDraft').onclick=async()=>{const values=draftValues();if(!values.notes.trim()){$('#draftState').textContent='Add a drafting brief first.';$('#draftNotes').focus();return;}draftLock(true);$('#draftState').textContent='Preparing suggested wording…';try{const proposed=await post('/api/email-drafts/generate',{brief:values.notes,subject:values.subject,body:values.body,model:$('#llmModel').value});showDialog('Suggested wording',`<p class="notice">Review this suggestion before using it. Your sender and recipient details are kept as entered.</p><pre>${esc('Subject: '+proposed.subject+'\n\n'+proposed.body)}</pre><button class="btn primary" id="useDraftWording">Use this wording</button>`);$('#useDraftWording').onclick=()=>{$('#draftSubject').value=proposed.subject;$('#draftBody').value=proposed.body;markDraftDirty();$('#reviewDialog').close();};$('#draftState').textContent='Suggestion ready for review.';}catch(e){$('#draftState').textContent=e.message+' You can continue editing manually.';}finally{draftLock(false);}};
load();
